In [19]:
import matplotlib.pyplot as plt
import pandas as pd
from path import Path

In [20]:
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder,OneHotEncoder 
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [21]:
# Load data
file_path=Path("chocolate_version1.csv")
chocolate_df = pd.read_csv(file_path)

chocolate_df.head()

,Unnamed: 0,company_location,country_of_bean_origin,cocoa_percent,rating,counts_of_ingredients,cocoa_butter,vanilla,lecithin,salt,sugar,sweetener_without_sugar
0,0,U.S.A,Madagascar,76.0,4.0,3,have_cocoa_butter,have_not_vanila,have_not_lecithin,have_not_salt,have_sugar,have_not_sweetener_without_sugar
1,1,U.S.A,Dominican republic,76.0,4.0,3,have_cocoa_butter,have_not_vanila,have_not_lecithin,have_not_salt,have_sugar,have_not_sweetener_without_sugar
2,2,U.S.A,Tanzania,76.0,3.0,3,have_cocoa_butter,have_not_vanila,have_not_lecithin,have_not_salt,have_sugar,have_not_sweetener_without_sugar
3,3,France,Peru,63.0,4.0,4,have_cocoa_butter,have_not_vanila,have_lecithin,have_not_salt,have_sugar,have_not_sweetener_without_sugar
4,4,France,Bolivia,70.0,4.0,4,have_cocoa_butter,have_not_vanila,have_lecithin,have_not_salt,have_sugar,have_not_sweetener_without_sugar

In [4]:
uniqueCompLoc=chocolate_df['company_location'].unique()
print(uniqueCompLoc)

['U.S.A' 'France' 'Fiji' 'Vanuatu' 'Ecuador' 'Mexico' 'Switzerland'
 'Netherlands' 'Spain' 'Peru' 'Canada' 'Italy' 'Brazil' 'Nicaragua' 'U.k.'
 'Australia' 'Philippines' 'Wales' 'Belgium' 'Vietnam' 'Germany'
 'Singapore' 'Venezuela' 'Malaysia' 'Russia' 'South korea' 'Taiwan'
 'Puerto rico' 'Colombia' 'Japan' 'New zealand' 'Costa rica' 'Hungary'
 'Scotland' 'Martinique' 'Sao tome' 'St. lucia' 'Guatemala' 'South africa'
 'Dominican republic' 'Sao tome & principe' 'Bolivia' 'Portugal' 'Norway'
 'Denmark' 'Grenada' 'Israel' 'India' 'St.vincent-grenadines'
 'Czech republic' 'Thailand' 'Finland' 'Madagascar' 'Sweden' 'Poland'
 'Austria' 'Honduras' 'U.a.e.' 'Lithuania' 'Ireland' 'Chile' 'Ghana'
 'Iceland' 'Argentina' 'Suriname' 'El salvador']

In [22]:
uniqueBeanOrigin=chocolate_df['country_of_bean_origin'].unique()
print(uniqueBeanOrigin)

['Madagascar' 'Dominican republic' 'Tanzania' 'Peru' 'Bolivia' 'Venezuela'
 'Ecuador' 'Brazil' 'Papua new guinea' 'Burma' 'Panama' 'Colombia' 'Cuba'
 'Togo' 'Sao tome' 'Mexico' 'Fiji' 'Vanuatu' 'Indonesia' 'Trinidad'
 'Vietnam' 'Nicaragua' 'Ghana' 'Belize' 'Blend' 'Grenada' 'Jamaica'
 'Guatemala' 'Costa rica' 'Honduras' 'Haiti' 'India' 'Congo' 'Philippines'
 'Solomon islands' 'Uganda' 'Malaysia' 'Sri lanka' 'Ivory coast' 'Gabon'
 'Taiwan' 'Puerto rico' 'Martinique' 'St. lucia' 'Australia' 'Liberia'
 'Sierra leone' 'Nigeria' 'U.s.a.' 'St.vincent-grenadines' 'Thailand'
 'Tobago' 'Bolvia' 'Sumatra' 'El salvador' 'Cameroon' 'Samoa'
 'Sao tome & principe' 'Principe' 'Sulawesi' 'Suriname' 'Dr congo']

In [23]:
chocolate_df['company_location'].value_counts(normalize=True)

U.S.A                    0.426259
France                   0.075090
Canada                   0.071043
U.k.                     0.052608
Italy                    0.030126
                           ...
Wales                    0.000450
Ghana                    0.000450
St.vincent-grenadines    0.000450
Russia                   0.000450
Suriname                 0.000450
Name: company_location, Length: 66, dtype: float64

In [24]:
chocolate_df['company_location'].value_counts()

U.S.A                    948
France                   167
Canada                   158
U.k.                     117
Italy                     67
                        ...
Wales                      1
Ghana                      1
St.vincent-grenadines      1
Russia                     1
Suriname                   1
Name: company_location, Length: 66, dtype: int64

In [25]:
chocolate_df['country_of_bean_origin'].value_counts()

Venezuela                238
Peru                     207
Dominican republic       200
Ecuador                  194
Madagascar               157
                        ...
Tobago                     1
St.vincent-grenadines      1
Martinique                 1
Gabon                      1
Dr congo                   1
Name: country_of_bean_origin, Length: 62, dtype: int64

In [26]:
chocolate_df['country_of_bean_origin'].value_counts(normalize=True)

Venezuela                0.107014
Peru                     0.093076
Dominican republic       0.089928
Ecuador                  0.087230
Madagascar               0.070594
                           ...
Tobago                   0.000450
St.vincent-grenadines    0.000450
Martinique               0.000450
Gabon                    0.000450
Dr congo                 0.000450
Name: country_of_bean_origin, Length: 62, dtype: float64

In [27]:
chocolate_df['company_location'] = chocolate_df['company_location'].astype('category')

others = chocolate_df['company_location'].value_counts().index[20:]
label = 'Other'

chocolate_df['company_location'] = chocolate_df['company_location'].cat.add_categories([label])
chocolate_df['company_location'] = chocolate_df['company_location'].replace(others, label)

In [33]:
#write custom encoder for company location
company_locations = {
    "U.S.A" : 1,
    "France": 2,
    "Canada": 3,
    "U.k.": 4,
    "Italy": 5,
    "Belgium": 6,
    "Australia": 7,
    "Ecuador": 8,
    "Switzerland": 9,
    "Germany": 10,
    "Spain": 11,
    "Denmark": 12,
    "Venezuela": 13,
    "Austria": 14,
    "New zealand": 15,
    "Japan": 16,
    "Hungary": 17,
    "Colombia":18,
    "Brazil": 19,
    "Netherlands": 20,
    "Other": 21
}

In [34]:
chocolate_df["company_location"] = chocolate_df["company_location"].apply(lambda x: company_locations[x])

In [37]:
chocolate_df.head(10)

,Unnamed: 0,company_location,country_of_bean_origin,cocoa_percent,rating,counts_of_ingredients,cocoa_butter,vanilla,lecithin,salt,sugar,sweetener_without_sugar
0,0,1,Madagascar,76.0,4.0,3,have_cocoa_butter,have_not_vanila,have_not_lecithin,have_not_salt,have_sugar,have_not_sweetener_without_sugar
1,1,1,Dominican republic,76.0,4.0,3,have_cocoa_butter,have_not_vanila,have_not_lecithin,have_not_salt,have_sugar,have_not_sweetener_without_sugar
2,2,1,Tanzania,76.0,3.0,3,have_cocoa_butter,have_not_vanila,have_not_lecithin,have_not_salt,have_sugar,have_not_sweetener_without_sugar
3,3,2,Peru,63.0,4.0,4,have_cocoa_butter,have_not_vanila,have_lecithin,have_not_salt,have_sugar,have_not_sweetener_without_sugar
4,4,2,Bolivia,70.0,4.0,4,have_cocoa_butter,have_not_vanila,have_lecithin,have_not_salt,have_sugar,have_not_sweetener_without_sugar
5,5,2,Venezuela,70.0,4.0,4,have_cocoa_butter,have_not_vanila,have_lecithin,have_not_salt,have_sugar,have_not_sweetener_without_sugar
6,6,2,Peru,63.0,4.0,3,have_cocoa_butter,have_not_vanila,have_not_lecithin,have_not_salt,have_sugar,have_not_sweetener_without_sugar
7,7,2,Ecuador,70.0,4.0,4,have_cocoa_butter,have_not_vanila,have_lecithin,have_not_salt,have_sugar,have_not_sweetener_without_sugar
8,8,2,Peru,70.0,4.0,4,have_cocoa_butter,have_not_vanila,have_lecithin,have_not_salt,have_sugar,have_not_sweetener_without_sugar
9,9,2,Brazil,70.0,3.0,4,have_cocoa_butter,have_not_vanila,have_lecithin,have_not_salt,have_sugar,have_not_sweetener_without_sugar

In [38]:
#write custom encode for bean origin
chocolate_df['country_of_bean_origin'] = chocolate_df['country_of_bean_origin'].astype('category')

others = chocolate_df['country_of_bean_origin'].value_counts().index[20:]
label = 'Other'

chocolate_df['country_of_bean_origin'] = chocolate_df['country_of_bean_origin'].cat.add_categories([label])
chocolate_df['country_of_bean_origin'] = chocolate_df['country_of_bean_origin'].replace(others, label)

In [41]:
chocolate_df.head(10)

,Unnamed: 0,company_location,country_of_bean_origin,cocoa_percent,rating,counts_of_ingredients,cocoa_butter,vanilla,lecithin,salt,sugar,sweetener_without_sugar
0,0,1,Madagascar,76.0,4.0,3,have_cocoa_butter,have_not_vanila,have_not_lecithin,have_not_salt,have_sugar,have_not_sweetener_without_sugar
1,1,1,Dominican republic,76.0,4.0,3,have_cocoa_butter,have_not_vanila,have_not_lecithin,have_not_salt,have_sugar,have_not_sweetener_without_sugar
2,2,1,Tanzania,76.0,3.0,3,have_cocoa_butter,have_not_vanila,have_not_lecithin,have_not_salt,have_sugar,have_not_sweetener_without_sugar
3,3,2,Peru,63.0,4.0,4,have_cocoa_butter,have_not_vanila,have_lecithin,have_not_salt,have_sugar,have_not_sweetener_without_sugar
4,4,2,Bolivia,70.0,4.0,4,have_cocoa_butter,have_not_vanila,have_lecithin,have_not_salt,have_sugar,have_not_sweetener_without_sugar
5,5,2,Venezuela,70.0,4.0,4,have_cocoa_butter,have_not_vanila,have_lecithin,have_not_salt,have_sugar,have_not_sweetener_without_sugar
6,6,2,Peru,63.0,4.0,3,have_cocoa_butter,have_not_vanila,have_not_lecithin,have_not_salt,have_sugar,have_not_sweetener_without_sugar
7,7,2,Ecuador,70.0,4.0,4,have_cocoa_butter,have_not_vanila,have_lecithin,have_not_salt,have_sugar,have_not_sweetener_without_sugar
8,8,2,Peru,70.0,4.0,4,have_cocoa_butter,have_not_vanila,have_lecithin,have_not_salt,have_sugar,have_not_sweetener_without_sugar
9,9,2,Brazil,70.0,3.0,4,have_cocoa_butter,have_not_vanila,have_lecithin,have_not_salt,have_sugar,have_not_sweetener_without_sugar

In [42]:
bean_origin = {
    "Venezuela" : 1,
    "Peru": 2,
    "Dominican republic": 3,
    "Ecuador": 4,
    "Madagascar": 5,
    "Blend": 6,
    "Nicaragua": 7,
    "Brazil": 8,
    "Bolivia": 9,
    "Belize": 10,
    "Colombia": 11,
    "Vietnam": 12,
    "Tanzania": 13,
    "Guatemala": 14,
    "Papua new guinea": 15,
    "Mexico": 16,
    "Costa rica": 17,
    "Trinidad":18,
    "Ghana": 19,
    "U.s.a": 20,
    "Other": 21
}

In [43]:
chocolate_df["country_of_bean_origin"] = chocolate_df["country_of_bean_origin"].apply(lambda x: bean_origin[x])

In [64]:
chocolate_df.head(10)

,Unnamed: 0,company_location,country_of_bean_origin,cocoa_percent,rating,counts_of_ingredients,cocoa_butter,vanilla,lecithin,salt,sugar,sweetener_without_sugar
0,0,1,5,76.0,4.0,3,have_cocoa_butter,have_not_vanila,have_not_lecithin,have_not_salt,have_sugar,have_not_sweetener_without_sugar
1,1,1,3,76.0,4.0,3,have_cocoa_butter,have_not_vanila,have_not_lecithin,have_not_salt,have_sugar,have_not_sweetener_without_sugar
2,2,1,13,76.0,3.0,3,have_cocoa_butter,have_not_vanila,have_not_lecithin,have_not_salt,have_sugar,have_not_sweetener_without_sugar
3,3,2,2,63.0,4.0,4,have_cocoa_butter,have_not_vanila,have_lecithin,have_not_salt,have_sugar,have_not_sweetener_without_sugar
4,4,2,9,70.0,4.0,4,have_cocoa_butter,have_not_vanila,have_lecithin,have_not_salt,have_sugar,have_not_sweetener_without_sugar
5,5,2,1,70.0,4.0,4,have_cocoa_butter,have_not_vanila,have_lecithin,have_not_salt,have_sugar,have_not_sweetener_without_sugar
6,6,2,2,63.0,4.0,3,have_cocoa_butter,have_not_vanila,have_not_lecithin,have_not_salt,have_sugar,have_not_sweetener_without_sugar
7,7,2,4,70.0,4.0,4,have_cocoa_butter,have_not_vanila,have_lecithin,have_not_salt,have_sugar,have_not_sweetener_without_sugar
8,8,2,2,70.0,4.0,4,have_cocoa_butter,have_not_vanila,have_lecithin,have_not_salt,have_sugar,have_not_sweetener_without_sugar
9,9,2,8,70.0,3.0,4,have_cocoa_butter,have_not_vanila,have_lecithin,have_not_salt,have_sugar,have_not_sweetener_without_sugar

In [45]:
chocolate_df.to_csv('chocolate_encoded_countries.csv')

In [56]:
#get dummies for string characters
X = pd.get_dummies(chocolate_df, columns=['cocoa_butter', 'vanilla', 'lecithin', 'salt', 'sugar','sweetener_without_sugar']).drop('rating', axis=1)

# Create target
y = chocolate_df['rating']
X.head(10)

,Unnamed: 0,company_location,country_of_bean_origin,cocoa_percent,counts_of_ingredients,cocoa_butter_have_cocoa_butter,cocoa_butter_have_not_cocoa_butter,vanilla_have_not_vanila,vanilla_have_vanila,lecithin_have_lecithin,lecithin_have_not_lecithin,salt_have_not_salt,salt_have_salt,sugar_have_not_sugar,sugar_have_sugar,sweetener_without_sugar_have_not_sweetener_without_sugar,sweetener_without_sugar_have_sweetener_without_sugar
0,0,1,5,76.0,3,1,0,1,0,0,1,1,0,0,1,1,0
1,1,1,3,76.0,3,1,0,1,0,0,1,1,0,0,1,1,0
2,2,1,13,76.0,3,1,0,1,0,0,1,1,0,0,1,1,0
3,3,2,2,63.0,4,1,0,1,0,1,0,1,0,0,1,1,0
4,4,2,9,70.0,4,1,0,1,0,1,0,1,0,0,1,1,0
5,5,2,1,70.0,4,1,0,1,0,1,0,1,0,0,1,1,0
6,6,2,2,63.0,3,1,0,1,0,0,1,1,0,0,1,1,0
7,7,2,4,70.0,4,1,0,1,0,1,0,1,0,0,1,1,0
8,8,2,2,70.0,4,1,0,1,0,1,0,1,0,0,1,1,0
9,9,2,8,70.0,4,1,0,1,0,1,0,1,0,0,1,1,0

In [57]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [58]:
# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=100, random_state=78)

In [59]:
# Fitting the model
rf_model = rf_model.fit(X, y)

In [60]:
# Making predictions using the testing data.
predictions = rf_model.predict(X)

In [61]:
# Calculating the confusion matrix.
cm = confusion_matrix(y, predictions)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 1", "Actual 2", "Actual 3", "Actual 4"], columns=["Predicted 1", "Predicted 2","Predicted 3", "Predicted 4" ])

cm_df

          Predicted 1  Predicted 2  Predicted 3  Predicted 4
Actual 1            1            0            0            0
Actual 2            0          198            0            0
Actual 3            0            0         1170            0
Actual 4            0            0            0          855

In [62]:
# Calculating the accuracy score.
acc_score = accuracy_score(y, predictions)

In [63]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y, predictions))

Confusion Matrix

          Predicted 1  Predicted 2  Predicted 3  Predicted 4
Actual 1            1            0            0            0
Actual 2            0          198            0            0
Actual 3            0            0         1170            0
Actual 4            0            0            0          855

Accuracy Score : 1.0
Classification Report
              precision    recall  f1-score   support

         1.0       1.00      1.00      1.00         1
         2.0       1.00      1.00      1.00       198
         3.0       1.00      1.00      1.00      1170
         4.0       1.00      1.00      1.00       855

    accuracy                           1.00      2224
   macro avg       1.00      1.00      1.00      2224
weighted avg       1.00      1.00      1.00      2224